<?php
$en=array(
    'Please do not request it illegally',
    'Parameter error',
    'Equipment error, please contact customer service',
    'Find a business card',
    'Click to open immediately',
    'No data is modified',
    'Business card does not exist!',
    'modified Successfully ',
    'fail to edit',
    'The amount of the recharge is incorrect',
    'Pre-payment failure',
    'Original Blue - red envelope',
    'Please select the red envelope type',
    'Please enter the number of red envelope',
    'Please enter the amount of red envelope',
    'Each red envelope minimum 0.01 yuan',
    'The amount of a single red envelope can not exceed 100',
    'Congratulations to make a fortune, great luck!',
    'Failed to create, please try again later',
    'Reply to success',
    'Reply failed',
    'The review was successful',
    'the review failed',
    'The group is abnormal. Please try again later',
    'The member has added a group',
    'The group is in progress',
    'Group successfully',
    'You have successfully joined the group',
    'The team has been dissolved, please re-apply',
    'You have added a group',
    'You are not the head of the group can not be dissociated',
    'The group was disbanded',
    'Your group has been disbanded',
    'success',
    'failure',
    'Successful operation',
    'operation failed',
    'Please create a group first',
    'Please select the user',
    'Group invitations',
    'Invite you to join the group',
    'Apply to join the group',
    'Group alarm',
    'You lost contact with your head',
    'Lost contact with you',
    'You are not currently in the group currently',
    'You have been in the group, can not repeat the group',
    'Please input the group name',
    'Please input a tour plan',
    'Please input the contact cellphone number',
    'Location error',
    'You have opened the group, can not repeat the group',
    'Device exception, please try again later',
    'Product exception, please contact customer service',
    'please input a valid phone number',
    'Please input the description of the missing person',
    'Please input the discovery address',
    'Sent successfully',
    'Failed to send',
    'Please fill in the description of the lost people',
    'Please fill in where to lose',
    'Please fill in lost people\'s photos',
    'Please fill in the lost time',
    'Please fill in the lost people\'s name',
    'Please fill in the contact name',
    'Please fill in the contact cellphone number',
    'please select the region',
    'You have not bound the device. Please bind the device first',
    'Device exception Please log in again',
    'Replacement success',
    'Replacement failed',
    'You have not bound the luggage, please bind first',
    'Data is abnormal, please try again later',
    'You can not delete a system tag',
    'deleted successfully',
    'failed to delete',
    'The tag already exists',
    'Add failed, please try again later',
    'Can not modify someone else\'s business card',
    'Bluetooth technology',
    'Set up successfully',
    'Set up failed',
    'Can not delete someone else\'s business card',
    'Please fill in the name of the business card',
    'Please fill in the position',
    'Please fill in cellphone number',
    'Add successful',
    'add failed',
    'Account abnormal, please try again later',
    'Equipment information is abnormal, please contact customer service',
    'wrong password',
    'The device has been bound',
    'You have already bound the device',
    'Bind successful',
    'Bind failed',
    'You have not bound the device yet',
    'Device information is abnormal. Please try again later',
    'Unbind successfully',
    'Unbind failed',
    'Account abnormal, please re-login',
    'Sunday',
    'Monday',
    'Tuesday',
    'Wednesday',
    'Thursday',
    'Friday',
    'Saturday',
    'Original Blue',
    'Your luggage with a core control',
    'Bluetooth device',
    'Shake to a red envelope',
    'Poke and snatch the red envelope immediately',
    'A group of information',
    'From the surrounding users',
    'A lost message',
    'E-mail format is incorrect',
    'Bind the mailbox is not correct',
    '[Bluetooth logo] Mailbox bind verification',
    '[Bluetooth logo] Password modify verification',
    '[jefferson] Unmount mailbox verification',
    '[jefferson] registration verification',
    '[jefferson] verification',
    'Click link verification',
    'The mailbox has been used',
    'update completed',
    'Update failed, please try again later',
    'Verification code',
    'Valid for 10 minutes, please fill in!',
    '[jefferson] verification code',
    'Account must be mobile phone number or mailbox',
    'Please fill in the account number and password',
    'The mailbox has been registered',
    'The phone number has been registered',
    'registration failed, please try again later',
    'registration successfully',
    'male',
    'Female',
    'Please fill in the account number',
    'Please fill in the password',
    'The account does not exist, please re-fill',
    'Password is wrong, please re-fill',
    'Log in failed, please try again later',
    'Your account is in the review stage. Please try to log in later',
    'The account does not exist, please register and then try to log in',
    'Your account review failed, please contact our customer service',
    'Account does not exist, please verify and log in again',
    'No account information',
    'The server is busy Please try again later',
    'Old password input incorrectly',
    'Hello there!',
    'Thanks for choosing to use smart blue, click the link below to verify your email:',
    'Jefferson technology mailbox verification',
    'If you have not registered the Original blue, please ignore this message',
    'If you have questions, please contact us:',
    'Mailbox verification error',
    'Account abnormal, please contact customer service',
    'Mailbox verification code error',
    'verification failed',
    'Verification is successful',
    'User does not exist',
    'You have not verified your emailbox. Please verify it first',
    'The mailbox is incorrect',
    'Password reset complete',
    'Password modification failed',
    'do not find the equipment, please contact customer service',
    'Please input your account number',
    'Parameter is incorrect',
    'Mailbox binding is successful',
    'Mailbox binding failed',
    'successful',
    'failed',
    'Please fill in your comments and suggestions',
    'We have received your feedback',
    'We have received  your feedback sincerely',
    'new function',
    'Fix the bug',
    'Optimized performance',
    'The maximum file limit is 2M',
    'Parameter is incomplete',
    'Items do not exist',
    'Items are being used can not be deleted',
    'The itinerary does not exist',
    'Please fill in the title',
    'Please fill in the contents',
    'Can not modify someone else\'s itinerary',
    'successfully deleted',
    'failed to delete',
    'Please fill in the itinerary title',
    'Please fill in the starting point',
    'Please fill in your destination',
    'Please fill in the departure time',
    'Please fill in the return time',
    'No such itinerary',
    'has not started',
    'processing',
    'over',
    'The device information you are connected is abnormal and try again later',
    'do not find the equipment, please contact customer service',
    'Must be a cellphone number',
    'You have bound the device',
    'The device is not connected, try again after connecting',
    'Please enter the correct mailbox',
    'New function',
    'Repair the Bug',
    'Optimize the performance');
$ch=array(
    '请勿非法请求',
    '参数错误',
    '设备异常，请联系客服',
    '发现一张名片',
    '点击立即打开',
    '没有数据被修改',
    '名片不存在！',
    '修改成功',
    '修改失败',
    '充值金额有误',
    '预支付失败',
    '初蓝-发红包',
    '请选择红包类型',
    '请输入红包个数',
    '请输入红包金额',
    '每个红包最小为0.01元',
    '单个红包金额不能超过100',
    '恭喜发财，大吉大利！',
    '创建失败，请稍后重试',
    '回复成功',
    '回复失败',
    '评论成功',
    '评论失败',
    '组团异常，请稍后再试',
    '该会员已经添加了组团',
    '组团进行中',
    '组团成功',
    '您已经成功加入组团',
    '该团已经解散，请重新申请',
    '您已经添加了组团',
    '您不是团长，不能解散他人组团',
    '组团解散',
    '您所在的组团已经解散',
    '成功',
    '失败',
    '操作成功',
    '操作失败',
    '请先创建组团',
    '请选择用户',
    '组团邀请',
    '邀请你加入组团',
    '申请加入组团',
    '组团警报',
    '您与团长失去联系',
    '与您失去联系',
    '您当前还未组团',
    '您已经在组团中，无法重复加团',
    '请输入团名称',
    '请输入团计划行程',
    '请输入联系电话',
    '位置信息错误',
    '您已经开团，不能重复开团',
    '设备异常，请稍后再试',
    '产品异常，请联系客服',
    '请输入正确的手机号',
    '请输入发现丢失人描述',
    '请输入发现地址',
    '发送成功',
    '发送失败',
    '请填写丢失人描述',
    '请填写丢失地址',
    '请填写丢失人照片',
    '请填写丢失时间',
    '请填写丢失人姓名',
    '请填写联系人姓名',
    '请填写联系人手机',
    '请选择地区',
    '您还未绑定设备，请先绑定设备',
    '设备异常请重新登录',
    '更换成功',
    '更换失败',
    '您还未绑定该箱包，请先绑定',
    '数据异常，请稍后重试',
    '不能删除系统标签',
    '删除成功',
    '删除失败',
    '该标签已经存在',
    '添加失败，请稍后重试',
    '不能修改他人名片',
    '蓝牙科技',
    '设置成功',
    '设置失败',
    '不能删除他人名片',
    '请填写名片姓名',
    '请填写职位',
    '请填写手机号码',
    '添加成功',
    '添加失败',
    '账号异常，请稍后再试',
    '设备信息异常，请联系客服',
    '密码错误',
    '该设备已经被绑定',
    '您已经绑定了该设备',
    '绑定成功',
    '绑定失败',
    '您还未绑定该设备',
    '设备信息异常，请稍后再试',
    '解除绑定成功',
    '解除绑定失败',
    '账号异常，请重新登录',
    '星期日',
    '星期一',
    '星期二',
    '星期三',
    '星期四',
    '星期五',
    '星期六',
    '初蓝',
    '你的箱包用芯控',
    '蓝牙设备',
    '摇到一个红包',
    '戳开立即抢红包',
    '一个组团信息',
    '来自周边的用户',
    '一个丢失信息',
    '邮箱格式不正确',
    '绑定的邮箱不正确',
    '[蓝牙logo]邮箱绑定验证',
    '[蓝牙logo]密码修改验证',
    '[jefferson]解除邮箱验证',
    '[jefferson]注册验证',
    '[jefferson]验证',
    '点击链接验证',
    '邮箱已被使用',
    '更新成功',
    '更新失败,请稍后再试',
    '验证码',
    '10分钟内有效，请及时填写！',
    '[jefferson]验证码',
    '账号必须为手机号码或者邮箱',
    '请填写账号和密码',
    '邮箱已被注册',
    '手机号码已被注册',
    '注册失败，请稍后再试',
    '注册成功',
    '男',
    '女',
    '请填写账号',
    '请填写密码',
    '该账号不存在,请重新填写',
    '密码错误,请重新填写',
    '登录失败，请稍后再试',
    '您的账户正处审核阶段，请稍后再尝试登录',
    '该账号不存在，请注册后再尝试登录',
    '您的账户审核失败，请联系我们的客服',
    '账户不存在，请核实后再次登录',
    '暂无此账号信息',
    '服务器繁忙请稍后再尝试',
    '旧密码输入错误',
    '你好！',
    '感谢选择使用蓝牙xx，点击下面链接以验证邮箱：',
    '杰富绅科技邮箱验证',
    '如果你没有注册过初蓝，请忽略此邮件。',
    '如有疑问请联系我们：',
    '邮箱验证信息错误',
    '账号异常，请联系客服',
    '邮箱验证码错误',
    '验证失败',
    '验证成功',
    '用户不存在',
    '您还没有验证邮箱，请先验证',
    '邮箱不正确',
    '密码修改成功',
    '密码修改失败',
    '暂未找到该设备，请联系客服',
    '请输入注册帐号',
    '参数不正确',
    '邮箱绑定成功',
    '邮箱绑定失败',
    '解除成功',
    '解除失败',
    '请填写您的意见和建议',
    '我们已经收到您的反馈',
    '我们已收到并诚恳的接受您的反馈',
    '新增功能',
    '修复了Bug',
    '优化了性能',
    '文件最大限制为2M',
    '参数不完整',
    '物品不存在',
    '物品正在使用不能刪除',
    '行程不存在',
    '请填写标题',
    '请填写内容',
    '不能修改他人行程',
    '刪除成功',
    '刪除失败',
    '请填写行程标题',
    '请填写出发地',
    '请填写目的地',
    '请填写出发时间',
    '请填写返回时间',
    '暂无此行程',
    '未开始',
    '进行中',
    '已结束',
    '您连接的设备信息异常，稍后再试',
    '暂未找到该设备，请联系客服',
    '必须为手机号码',
    '您已绑定该设备',
    '设备未连接，连接后再试',
    '请输入正确邮箱',
    '新增功能',
    '修复了Bug',
    '优化了性能');

function Language($lang){
    global $ch;
    global $en;
    return $lang==2?$ch:$en;
}